// <auto-generated />
using System;
using CitiesManager.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.Core.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcee3462-1512-4fc3-98cf-dbfbccf1e919"),
                            Name = "London"
                        },
                        new
                        {
                            Id = new Guid("b9bb7cd6-7969-4fc0-8dae-b7ef7c9c6580"),
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = new Guid("8467e78c-bf7d-443b-9e7d-e07848e6a6a4"),
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("d9ee6f5f-5dbe-4356-8c78-af1532ac8fbc"),
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = new Guid("0edbd081-15ef-4679-a5f4-5d000aaf2b4e"),
                            Name = "Prague"
                        },
                        new
                        {
                            Id = new Guid("08a84aab-9084-4179-9e9d-9d43de5546fc"),
                            Name = "Kyiv"
                        },
                        new
                        {
                            Id = new Guid("8f8c9266-193d-4a63-ac50-1db0954c9c5e"),
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("cdea0ec1-4f3a-4c0a-8804-a9acc278c78b"),
                            Name = "Atlanta"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
